# fly.toml app configuration file generated for timesheet-magic-backend on 2025-05-29T17:27:20-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "timesheet-magic-backend"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"
  
[build.args]
  
[build.contexts]

[env]
  PORT = "8000"
  SUPABASE_URL = "https://mobzemfxlxydpocscpwz.supabase.co"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
